services:
  postgres:
    image: postgres:17
    container_name: novadesk-quarkus-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  novadesk-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: novadesk-quarkus-api
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: