quarkus.application.name=novadesk-api-quarkus

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

quarkus.smallrye-openapi.info-title=NovaDesk API
quarkus.smallrye-openapi.info-description=API REST para gerenciamento de chamados internos de help desk
quarkus.smallrye-openapi.info-version=1.0.0

quarkus.swagger-ui.always-include=true